### Dependencies

In [1]:
from bs4 import BeautifulSoup
import requests
import pymongo
from splinter import Browser
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import time # to be used to delay
import re
import glob

In [2]:
# executable_path = {'executable_path':'resources/chromedriver'}
executable_path = {'executable_path':ChromeDriverManager().install()}

# create a new browser object by default it is firefox the default one
browser = Browser('chrome', **executable_path, headless = False) #headless true will not open browser

[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 90.0.4430
[WDM] - Get LATEST driver version for 90.0.4430

[WDM] - Driver [C:\Users\gucas\.wdm\drivers\chromedriver\win32\90.0.4430.24\chromedriver.exe] found in cache

### Mass Shootings

In [3]:
mas_url = 'https://www.gunviolencearchive.org/mass-shooting'
browser.visit(mas_url)
for i in range(81):
    html = browser.html
    soup = BeautifulSoup(html, 'html.parser')
    time.sleep(1)
    mas_df = pd.read_html(html)
    time.sleep(1)
    mas_df= mas_df[1]
    time.sleep(1)
    #If no Next button found, exit loop
    try:
        browser.click_link_by_partial_text("next")
    except:
        break
    # Export to csv
    filepath = f"data/mas{i}.csv"
    mas_df.to_csv(filepath, index=False)
    print(f"Successfully scraped table from page {i}")

C:\Users\gucas\anaconda3\envs\PythonData\lib\site-packages\splinter\driver\webdriver\__init__.py:493: FutureWarning: browser.find_link_by_partial_text is deprecated. Use browser.links.find_by_partial_text instead.
  FutureWarning,

Successfully scraped table from page 0
Successfully scraped table from page 1
Successfully scraped table from page 2
Successfully scraped table from page 3
Successfully scraped table from page 4
Successfully scraped table from page 5
Successfully scraped table from page 6
Successfully scraped table from page 7
Successfully scraped table from page 8
Successfully scraped table from page 9
Successfully scraped table from page 10
Successfully scraped table from page 11
Successfully scraped table from page 12
Successfully scraped table from page 13
Successfully scraped table from page 14
Successfully scraped table from page 15
Successfully scraped table from page 16
Successfully scraped table from page 17
Successfully scraped table from page 18
Successfully scraped table from page 19
Successfully scraped table from page 20
Successfully scraped table from page 21
Successfully scraped table from page 22
Successfully scraped table from page 23
Successfully scraped table from page 24
Successfully scraped table from page 25
Successfully scraped table from page 26
Successfully scraped table from page 27
Successfully scraped table from page 28
Successfully scraped table from page 29
Successfully scraped table from page 30
Successfully scraped table from page 31
Successfully scraped table from page 32
Successfully scraped table from page 33
Successfully scraped table from page 34
Successfully scraped table from page 35
Successfully scraped table from page 36
Successfully scraped table from page 37
Successfully scraped table from page 38
Successfully scraped table from page 39
Successfully scraped table from page 40
Successfully scraped table from page 41
Successfully scraped table from page 42
Successfully scraped table from page 43
Successfully scraped table from page 44
Successfully scraped table from page 45
Successfully scraped table from page 46
Successfully scraped table from page 47
Successfully scraped table from page 48
Successfully scraped table from page 49
Successfully scraped table from page 50
Successfully scraped table from page 51
Successfully scraped table from page 52
Successfully scraped table from page 53
Successfully scraped table from page 54
Successfully scraped table from page 55
Successfully scraped table from page 56
Successfully scraped table from page 57
Successfully scraped table from page 58
Successfully scraped table from page 59
Successfully scraped table from page 60
Successfully scraped table from page 61
Successfully scraped table from page 62
Successfully scraped table from page 63
Successfully scraped table from page 64
Successfully scraped table from page 65
Successfully scraped table from page 66
Successfully scraped table from page 67
Successfully scraped table from page 68
Successfully scraped table from page 69
Successfully scraped table from page 70
Successfully scraped table from page 71
Successfully scraped table from page 72
Successfully scraped table from page 73
Successfully scraped table from page 74
Successfully scraped table from page 75
Successfully scraped table from page 76
Successfully scraped table from page 77
Successfully scraped table from page 78

In [4]:
final_mas = pd.DataFrame()

for filepath in glob.iglob(r'C:\Users\gucas\Crime-Project\data\**\*.csv', recursive=True):
    df = pd.read_csv(filepath)
    final_mas = final_mas.append(df)

final_mas = final_mas.reset_index(drop=True)
final_mas.to_csv('data/final_mas.csv', index=False)

In [6]:
final_mas["Incident Date"] = pd.to_datetime(final_mas["Incident Date"])
final_mas

,Incident ID,Incident Date,State,City Or County,Address,# Killed,# Injured,Operations
1174,1206476,2018-09-09,Florida,Jacksonville,NaN,0,4,View Incident View Source
1172,1206409,2018-09-09,Illinois,Elgin,550 S McLean Blvd,1,3,View Incident View Source
1173,1206375,2018-09-09,Alabama,Auburn,224 W Magnolia St,1,4,View Incident View Source
1542,931139,2017-09-09,Alabama,Selma,Kings Bend Road,0,4,View Incident View Source
127,1788401,2020-09-08,Maryland,Baltimore,2300 block of Greenmount Ave,0,5,View Incident View Source
...,...,...,...,...,...,...,...,...
1367,1083011,2018-04-01,Alabama,Mobile,3556 Halls Mill Rd,1,4,View Incident View Source
1368,1082835,2018-04-01,Michigan,Saginaw,600 block of Yale St,0,5,View Incident View Source
1737,809815,2017-04-01,California,Pittsburg,100 block of Madoline Street,0,5,View Incident View Source
1738,809048,2017-04-01,Florida,Tampa,219 S Howard Ave,1,4,View Incident View Source
1739,809499,2017-04-01,Oklahoma,Oklahoma City,1200 block of N Woodward Avenue,2,3,View Incident View Source

In [7]:
final_mas = final_mas.sort_values("Incident Date",ascending=False)
final_mas

,Incident ID,Incident Date,State,City Or County,Address,# Killed,# Injured,Operations
0,1985432,2021-04-24,Louisiana,New Orleans,100 block of Bourbon St,0,5,View Incident View Source
1,1984807,2021-04-22,California,San Diego,500 block of J St,1,4,View Incident View Source
3,1982260,2021-04-19,Georgia,Atlanta,1191 Oakland Ln SW,0,5,View Incident View Source
2,1981805,2021-04-19,Texas,Houston,700 E Whitney St,2,4,View Incident View Source
7,1980689,2021-04-18,Wisconsin,Kenosha,1548 Sheridan Rd,3,3,View Incident View Source
...,...,...,...,...,...,...,...,...
1921,658226,2016-09-18,Pennsylvania,Pittsburgh,1700 block of Brighton Pl,0,4,View Incident View Source
1920,657854,2016-09-18,Pennsylvania,Philadelphia,3001 Castor Avenue,0,4,View Incident View Source
1922,657863,2016-09-18,Virginia,Lynchburg,421 Rivermont Ave,1,3,View Incident View Source
1924,659289,2016-09-17,Florida,Miami,20582 SW 119th Ave,0,6,View Incident View Source
1923,657634,2016-09-17,District of Columbia,Washington,2600 block of Birney Pl SE,2,7,View Incident View Source

In [9]:
final_mas["Incident Date"] = final_mas["Incident Date"].dt.strftime("%B %d, %Y")
final_mas

,Incident ID,Incident Date,State,City Or County,Address,# Killed,# Injured,Operations
0,1985432,"April 24, 2021",Louisiana,New Orleans,100 block of Bourbon St,0,5,View Incident View Source
1,1984807,"April 22, 2021",California,San Diego,500 block of J St,1,4,View Incident View Source
3,1982260,"April 19, 2021",Georgia,Atlanta,1191 Oakland Ln SW,0,5,View Incident View Source
2,1981805,"April 19, 2021",Texas,Houston,700 E Whitney St,2,4,View Incident View Source
7,1980689,"April 18, 2021",Wisconsin,Kenosha,1548 Sheridan Rd,3,3,View Incident View Source
...,...,...,...,...,...,...,...,...
1921,658226,"September 18, 2016",Pennsylvania,Pittsburgh,1700 block of Brighton Pl,0,4,View Incident View Source
1920,657854,"September 18, 2016",Pennsylvania,Philadelphia,3001 Castor Avenue,0,4,View Incident View Source
1922,657863,"September 18, 2016",Virginia,Lynchburg,421 Rivermont Ave,1,3,View Incident View Source
1924,659289,"September 17, 2016",Florida,Miami,20582 SW 119th Ave,0,6,View Incident View Source
1923,657634,"September 17, 2016",District of Columbia,Washington,2600 block of Birney Pl SE,2,7,View Incident View Source

In [10]:
final_mas.to_csv('data/final_mas_formatted_ordered.csv', index=False)

In [ ]:
# Close browser
browser.quit()